# Required KRaft settings
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@kafka_broker:9093

# Listeners
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
advertised.listeners=PLAINTEXT://kafka_broker:9092
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

# Log directories
log.dirs=/tmp/kraft-combined-logs

# Disk limits
log.retention.hours=1
log.segment.bytes=104857600
log.retention.bytes=536870912
